eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.105:8761/eureka/
server:
  port: 8764
spring:
  redis:
    host: 192.168.0.105
    port: 6379
  application:
    name: service-redis-lock