server:
  port: 8758
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: service_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: localhost:8848